config/routes.rb
Rails.application.routes.draw do
  root 'events#index'
  delete 'logout', to: 'sessions#destroy'
  get 'inbox', to: 'users#inbox'
  get 'user_events', to: 'users#user_created_events'
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create]
  resources :events, only: [:new, :create, :show, :index]
  resources :invitations, only: [:create, :update]
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :creator, class_name: 'User', foreign_key: 'user_id'
    has_many :invitations
    has_many :attendees, through: :invitations, source: :user

    validates :event_date, :title, :description, :venue, presence: true

    scope :upcoming_events, -> {where('event_date >= ?', Date.today)}
    scope :past_events, -> {where('event_date < ?', Date.today)}

    def confirmed_attendees(event_id)
        @event = Event.find(event_id)
        confirmed_guests = []
        @event.attendees.each do |attendee|
           invite = Invitation.where("user_id = ? AND event_id = ?", attendee.id, @event.id).first
           confirmed_guests << attendee if invite.status == "accepted"
        end
        confirmed_guests
    end

    def users_without_invites(event_id)
        event = Event.find(event_id)
        no_invites = User.all.to_a - event.attendees.to_a
        no_invites - [event.creator]
    end

    
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
    has_many :events
    has_many :invitations
    has_many :attended_event, through: :invitations, source: :event
    validates :username, presence: true
    
    
    def has_invite(event)
        attended_event.to_a.include?(event)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    before_action :require_login, only: [:new]
    def index
        @upcoming_events = Event.upcoming_events
        @past_events = Event.past_events
    end

    def new
        @event = Event.new
    end

    def create
        @event = current_user.events.build(event_params)
        if @event.save
            flash[:notice] = "Event successfully created"
            redirect_to @event
        else
            render 'new'
        end
    end

    def show
        @event = Event.find(params[:id])
        @guests = @event.users_without_invites(params[:id])
        @confirmed_guests = @event.confirmed_attendees(@event.id)
    end

    private

      def event_params
        params.require(:event).permit(:event_date,:title,:venue,:description)
      end

end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
    def create
        invited_guests = params[:guest]
        event_id = params[:event_id]
        
        invited_guests.each do |guest|
            @invited_guest = User.find(guest)
            msg = "Dear #{@invited_guest.username}, you have received an invitation to #{Event.find(event_id).title}"
            Invitation.create(user_id: guest, event_id: event_id, message: msg)
        end
        flash[:notice] = "Invites successfully sent"
        redirect_to events_path
    end

    def update
        @invitation = Invitation.find(params[:id])
        @invitation.update_column(:status, params[:status])
        if params[:status] == "accepted"
            flash[:notice] = "You accepted the invite to #{Event.find(@invitation.event_id).creator.username}\'s party. Invite more of your friends, check create guest list tab"
            redirect_to event_path(@invitation.event_id)
        else
            flash[:reject] = "You rejected the invite to #{Event.find(@invitation.event_id).creator.username}\'s party"
            redirect_to events_path
        end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:username])
    if user
      log_in user
      flash[:notice] = "You successfully signed in"
      redirect_to events_path 
    else
      flash.now[:error] = "Enter correct username / Sign up if you do not have an account"
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:notice] = "Welcome to EventSter"
      redirect_to events_path
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @created_events = @user.events
    @user_upcoming_events = @created_events.upcoming_events
    @upcoming_invited = @user.attended_event.upcoming_events
    @attended_events = @user.attended_event.past_events
  end

  def inbox
    @messages = current_user.invitations.all
  end

  def user_created_events
    @user = User.find(params[:id])
    @created_events = @user.events
  end

  private

  def user_params
    params.require(:user).permit(:username)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id
    end

    def log_out
        session.delete(:user_id)
        @current_user = nil
    end

    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end

    def logged_in?
        !current_user.nil?
    end

    def require_login
        redirect_to new_session_path if current_user.nil?
    end
    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_event.html.erb
<div class="event__card">
    <div class="card__header">
        <%= link_to event_path(event) do %>
            <%= image_tag 'Untitled-6.svg'%>
        <% end %>
    </div>
    <div class="event__info container">
        <%= link_to event_path(event) do%>
            <h4 class="sub-title"><%=event.title %></h4>
        <% end %>
        <P class="event_date"><%= event.event_date.strftime(" %a, %b %d, %Y" )%></P>
        <p>Venue : <%= event.venue%></p>
    </div>
</div>

app/views/events/index.html.erb
<main class='main'>
    <div class="main-wrapper container">
        <div class="hero row">
            <div class="hero__content">
                <h1 class="title">Bring everyone together.</h1>
                
                <p class="hero__content--text">Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo in qui illo commodi excepturi dolores, inventore ut corrupti ipsa magnam.</p>
                <button class="btn"><%= link_to "Create event", new_event_path %></button>
            </div>
            <div class="hero__vector__img">
               <%= image_tag 'block party 1.svg'%>
            </div>
        </div>
    
        <div class="upcoming__events event-section">
            <h2 class="title">Upcoming events</h2>
            <div class="upcoming__events--wrapper">
                <%=render partial:'event', collection: @upcoming_events%>
            </div>  
        </div>
        <div class="past__events event-section">
            <h2 class="title">Past events</h2>
            <div class="upcoming__events--wrapper">
                <%=render partial:'event', collection: @past_events%>
            </div> 
        </div>
    </div>
</main>

app/views/events/new.html.erb
<div class="container">
    <% if @event.errors.any? %>
        <p><%= pluralize(@event.errors.count, "Error")%> prevented this event from being created</p>

        <ul>
            <% @event.errors.full_messages.each do |msg|%>
            <li><%= msg%></li>
            <% end %>
        </ul>
    <% end %>
    <h1 class="title">Create your Event</h1>
    <%= form_with model: @event, local: true do |form|%>
        <%= form.label "Title"%>
        <%= form.text_field :title, class: "form-field"%>
    
        <%= form.label "Description"%>
        <%= form.text_area :description, class: "form-field"%>
    
        <%= form.label :event_date, "Date"%>
        <small>dd/mm/yyyy</small>
        <%= form.text_field :event_date, class: "form-field" %>
    
        <%= form.label "Venue"%>
        <%= form.text_field :venue, class: "form-field" %>
        <%= form.submit "Create event", class: "btn"%>
    <% end %>
</div>

app/views/events/show.html.erb
<div class="container row event__showpage">
    <div class="event__details">
        <div class="event"> 
            <div class="event__hero">
                <div class="event__hero--img">
                    <%= image_tag "block party 1.svg"%>
                </div>
                <div class='event__hero--sidebar'>
                    <div class="date">
                        <p><%= @event.event_date.strftime("%b")%></p>
                        <P><%= @event.event_date.strftime("%d")%></P>
                    </div>
                    <h4 class="title"><%= @event.title%></h4>
                    <small>by <%= link_to @event.creator.username, user_path(@event.creator),  class: "profile_link"%></small>
                </div>
            </div>
            <div class="event__description">
                <div class="description">
                    <h3 class="title">About this event</h3>
                    <p><%= @event.description%></p>
                </div>
                <div class="event__description--sidebar">
                    <h4>Date and time</h4>
                    <p class="date"><%= @event.event_date.strftime(" %a, %b %d, %Y" )%></p>
                    <p>Location</p>
                    <h4><%= @event.venue%></h4>
                </div>
            </div>
        </div>
        <div class="guest__list">
            <small>Only guests with invites will appear here, check inbox and accept invitation</small>
            <h2 class="title">Guest list</h2>
            
               <% @confirmed_guests.each do |guest|%>
                    <p><%= guest.username%></p>
               <% end %>
        </div>
    </div>
    <% if logged_in? && (current_user.has_invite(@event) || @event.creator.id == current_user.id) %>
    <div class="create__guestlist"> 
       <div class="add__guests">
            <h2 class="title">Create your guest list</h2>
            <%= form_with(url: invitations_path) do |form|%>
                <div class="guests">
                    <% @guests.each do |guest|%>
                        <div class="user__check row">
                            <p> <%= guest.username%></p>
                            <%= form.check_box("guest", {multiple: true}, guest.id,nil) %>
                        </div>
                    <% end %>
                </div>
                <%= form.submit "Send invites", class: "btn"%>
                <%= form.hidden_field :event_id, :value => @event.id%>
            <% end %>
       </div>
    </div>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Poppins&family=Roboto+Condensed:wght@300&display=swap" rel="stylesheet"> 
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'navigation/navigation'%>
    <%= render 'shared/flash'%>
    <%= yield %>
  </body>
</html>

app/views/navigation/_navigation.html.erb
<header class="header">
    <div class="header__wrapper container row">
        <p class="logo"><%= link_to "Logo", events_path%></p>
        <nav class="nav">
            <ul class="nav__items row">
                <li class="nav__link btn"><%= link_to "Host an event", new_event_path%></li>
                <% if logged_in? %>
                <li class="nav__link"><%= link_to "Profile", user_path(current_user) %></li>
                <div class="message__icon nav__link">
                    <%= link_to inbox_path do %>
                    <%= image_tag 'envelope.svg'%>
                    <small class="msg_received"><%= current_user.invitations.count%></small>
                    <% end %>
                </div>
               
                <% end %>
    
                <% if !logged_in?%>
                <li class="nav__link"><%= link_to "Sign In", new_session_path%></li>
                <% end %>
                <% if logged_in? %>
                <li class="nav__link"><%= link_to "Sign Out", logout_path, method: :delete%></li>
                <% end %>
            </ul>
        </nav>
    </div>
</header>

app/views/shared/_flash.html.erb
<div id = "flash-message">
    <div class="notice_wrapper container">
        <% flash.each do |key, value|%>
            <div class="notice__message <%= key%>">
                <%= value %>
            </div>
        <% end %>
    </div>
</div>

app/views/users/_user_event.html.erb
<div class="user__event">
    <div class="event-content container row">
        <div>
            <p><%= user_event.title%></p>
        </div>
        <p>invites sent: 200</p>
        <p>Confirmed: 20</p> 
    </div>
</div>

app/views/users/inbox.html.erb
<div class="container">
    <%@messages.each do |msg|%>
        <div class="message">
            <p><%= Event.find(msg.event_id).creator.username%></p>
            <p><%= msg.message%></p>
            <%= link_to "Accept", invitation_path(msg, status: "accepted"),method: :patch, class: "btn"%>
            <%= link_to "Decline",invitation_path(msg, status: "declined"),method: :patch, class: "decline"%>
        </div>
    <% end %>
</div>

app/views/users/new.html.erb
<div class="sign_in container ">
    <div class="sign_in_wrapper">
        <% if @user.errors.any? %>
            <% @user.errors.full_messages.each do |msg|%>
                <p class= "error-form"> <span class=error-asterix>*</span> <%= msg %></p>
            <% end %>
        <% end %>
        <h1 class="title">Sign up</h1>
        <div class="sign_in_form">
            <%= form_with model: @user, local: true do |form|%>
                <div class="form_elements">
                    <%= form.label :username, "Username"%>
                    <%= form.text_field :username, class: "username" %>
                    <%= form.submit "Sign in", class: "btn btn--sign"%>
                </div>
            <% end %>
        </div>    
    <p>Already have an account? <%= link_to "Sign In",new_session_path %></p>
    </div>
</div>

app/views/users/show.html.erb
<div class="user__profile container row">
    <div class="user__events">
        <div class="user__info">
            <p class="title"><%= @user.username%></p>
            <p>Events hosted: <%= @created_events.all.count%></p>
            <% if logged_in? && current_user.id == @user.id%>
            <p>Your upcoming events: <%= @user_upcoming_events.count%></p>
            <p>Invited upcoming events: <%= @upcoming_invited.count%></p>
            <% end %>
            <p>Invited events: <%= @user.invitations.count%></p>
            <p class=" btn"> <%= link_to "View events", user_events_path(id: @user.id)%></p>
           
        </div>
    </div>
    <div class="upcoming__events event-section upcoming__events--user">
        <div>
            <h2 class="title">Upcoming invited events</h2>
            <div class="upcoming__events--wrapper">
            	<%=render partial:'events/event', collection: @upcoming_invited%>
            </div> 
        </div> 
        <div>
            <h2 class="title">Past attended events</h2>
            <div class="upcoming__events--wrapper">
            	<%=render partial:'events/event', collection: @attended_events%>
            </div> 
        </div> 
    </div>

</div>

app/views/users/user_created_events.html.erb
<div class="container">
    <h2 class="title">Events Hosted</h2>
    <%= render partial: 'events/event', collection: @created_events%>
</div>